#!/usr/bin/env python3
"""
Generate secure secrets for production.
Run: python scripts/generate_secrets.py
"""

import secrets
import string
import argparse
from pathlib import Path


def generate_secret_key(length=50):
    """Generate a secure Django secret key."""
    return secrets.token_urlsafe(length)


def generate_password(length=32):
    """Generate a secure random password."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def generate_database_url():
    """Generate a PostgreSQL database URL."""
    db_password = generate_password(24)
    return f"postgresql://insighthub:{db_password}@postgres:5432/insighthub_prod"


def main():
    parser = argparse.ArgumentParser(description="Generate secure secrets for Insighthub")
    parser.add_argument("--output", "-o", default=".env.production", 
                       help="Output file for generated secrets")
    parser.add_argument("--force", "-f", action="store_true", 
                       help="Overwrite existing file")
    
    args = parser.parse_args()
    
    output_file = Path(args.output)
    
    if output_file.exists() and not args.force:
        print(f"⚠️  {output_file} already exists. Use --force to overwrite.")
        return
    
    secrets_content = f"""# Insighthub Production Secrets
# AUTOGENERATED - DO NOT COMMIT TO VERSION CONTROL

# Django
DJANGO_SECRET_KEY={generate_secret_key()}

# Database
DATABASE_URL={generate_database_url()}

# Redis
REDIS_URL=redis://redis:6379/0

# Celery
CELERY_BROKER_URL=redis://redis:6379/0

# External APIs (Add your own keys)
YELP_API_KEY=your-yelp-api-key-here
GOOGLE_PLACES_API_KEY=your-google-places-api-key-here

# Security
SECURE_SSL_REDIRECT=True
SECURE_HSTS_SECONDS=31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS=True
SECURE_HSTS_PRELOAD=True

# CORS (Configure for your domain)
CORS_ALLOWED_ORIGINS=https://app.insighthub.com

# Email
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=your-email@gmail.com
EMAIL_HOST_PASSWORD={generate_password(16)}
DEFAULT_FROM_EMAIL=Insighthub <noreply@insighthub.com>

# Sentry (Optional)
# SENTRY_DSN=your-sentry-dsn-here

# Logging
DJANGO_LOG_LEVEL=WARNING

# Generated on: {secrets.token_urlsafe(8)}
"""
    
    with open(output_file, 'w') as f:
        f.write(secrets_content)
    
    print(f"✅ Generated secure secrets in {output_file}")
    print("⚠️  Important:")
    print("   1. Add your API keys to the file")
    print("   2. Never commit this file to version control")
    print("   3. Store it securely (use git-secret or similar)")


if __name__ == "__main__":
    main()